name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (Linux clean install)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install dependencies (non-Linux)
        if: runner.os != 'Linux'
        run: npm ci

      - name: Run unit tests
        run: npm test -- --run
        env:
          ROLLUP_SKIP_NODEJS_NATIVE: '1'

      - name: Build
        run: npm run build
        env:
          ROLLUP_SKIP_NODEJS_NATIVE: '1'

  diagrams:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (Linux clean install)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install dependencies (non-Linux)
        if: runner.os != 'Linux'
        run: npm ci

      - name: Generate Mermaid SVG
        run: npm run docs:flow

      - name: Generate Mermaid PNG
        run: npm run docs:flow:png

      - name: Upload diagrams artifact
        uses: actions/upload-artifact@v4
        with:
          name: flow-diagrams
          path: |
            docs/flowchart.svg
            docs/flowchart.png
