name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: true
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install (lockfile)
        run: npm ci

      - name: Build
        run: npm run build

  diagrams:
    name: Generate diagrams
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    env:
      CI: true
      ROLLUP_SKIP_NODEJS_NATIVE: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install (lockfile)
        run: npm ci

      - name: Generate Mermaid SVG (soft-skip if missing)
        run: |
          if npm pkg get scripts.docs:flow | grep -qv null; then
            npm run docs:flow
          else
            echo "Skipping docs:flow (script not found)"
          fi

      - name: Generate Mermaid PNG (soft-skip if missing)
        run: |
          if npm pkg get scripts.docs:flow:png | grep -qv null; then
            npm run docs:flow:png
          else
            echo "Skipping docs:flow:png (script not found)"
          fi

      - name: Upload diagrams artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flow-diagrams
          path: |
            docs/flowchart.svg
            docs/flowchart.png
          retention-days: 7

